### ISSUE TITLE
Getting "The handshake operation timed out error".

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#120] opened 2023-03-17 20:07 UTC
I'm trying to run the simple gather_facts task one of the Switch and getting the below error. Need help to troubleshoot the issue.

FOS: v8.2.3c
Model: Brocade 6510

Playbook Task:

  - name: gather facts
    brocade_facts:
      credential:
        fos_ip_addr: "{{fos_ip_addr}}" 
        fos_user_name: test
        fos_password: "{{ ansible_password }}"
        https: True
      vfid: -1
      gather_subset:
        - brocade_time_clock_server
        - brocade_chassis_chassis

  - name: print ansible_facts gathered
    debug:
      var: ansible_facts  

TASK [gather facts] ************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <urlopen error _ssl.c:860: The handshake operation timed out>
fatal: [switcha]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 1349, in do_open\\n    encode_chunked=req.has_header('Transfer-encoding'))\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 1254, in request\\n    self._send_request(method, url, body, headers, encode_chunked)\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 1300, in _send_request\\n    self.endheaders(body, encode_chunked=encode_chunked)\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 1249, in endheaders\\n    self._send_output(message_body, encode_chunked=encode_chunked)\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 1036, in _send_output\\n    self.send(msg)\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 974, in send\\n    self.connect()\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 430, in connect\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 365, in wrap_socket\\n    _context=self, _session=session)\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 776, in __init__\\n    self.do_handshake()\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 1036, in do_handshake\\n    self._sslobj.do_handshake()\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 648, in do_handshake\\n    self._sslobj.do_handshake()\\nsocket.timeout: _ssl.c:860: The handshake operation timed out\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1679072953.272424-10-114556434191649/AnsiballZ_brocade_facts.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1679072953.272424-10-114556434191649/AnsiballZ_brocade_facts.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1679072953.272424-10-114556434191649/AnsiballZ_brocade_facts.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.brocade_facts', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\\", line 495, in <module>\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\\", line 269, in main\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\\", line 54, in login\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_url.py\\", line 242, in url_helper\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 1390, in open_url\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 1294, in open\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 223, in urlopen\\n    return opener.open(url, data, timeout)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 526, in open\\n    response = self._open(req, data)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 544, in _open\\n    '_open', req)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 504, in _call_chain\\n    result = func(*args)\\n  File \\"/tmp/ansible_brocade_facts_payload_c7e24q9p/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 448, in https_open\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 1351, in do_open\\n    raise URLError(err)\\nurllib.error.URLError: <urlopen error _ssl.c:860: The handshake operation timed out>\\n", "module_stdout": "", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by autocoder10** [comment] 2023-03-22 18:27
Any help with this issue is appreciated.

**Comment by prasad-valmeti-broadcom** [comment] 2023-05-01 21:32
What is the Ansible version used?
Please make sure the REST query is working for this switch with the provided credentials.
With https: True, any other ansible requests are getting succeeded?
What is the python version in your Ansible server? With python 3.10, there were some issues.
Please make sure the python version that you are using is less than python 3.10.

**Comment by prasad-valmeti-broadcom** [comment] 2023-05-23 21:02
Could you please let us know more details as requested?
In case if the issue is resolved, please update the status.

**Comment by prasad-valmeti-broadcom** [comment] 2023-09-08 22:57
Could you please let us know if there are any issues pending? If there are no issues, could you please let us know if we can close this issue?

**Comment by autocoder10** [comment] 2023-09-26 01:00
So sorry for the late reply. For now we can close this issue. Thank you!!

**Closed** 2023-09-29 05:25 UTC
