### ISSUE TITLE
Delete zoning module fails to delete zones.

### ISSUE THREAD

**Issue by rsndates** [brocade/ansible#21] opened 2020-03-31 21:01 UTC
When running the zoning to delete task I am constantly getting the following error.  I believe the zoning delete module needs to remove the zone from the configuration before deleting the zone.  Also If the zone doesnt exist should not throw an error.  

> 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "CFG ENABLE failed", "patch_resp_code": 400, "patch_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-1", "error-module": "zone"}, "error-message": "\"ZONE_brocade_idempotency_01\" not found", "error-path": "/effective-configuration/", "error-tag": "Operation-failed", "error-type": "protocol"}}}, "patch_resp_reason": "Bad Request", "patch_url": "http://<IP>/rest/running/zoning/effective-configuration?vf-id=1"}

**Comment by daniel-chung-broadcom** [comment] 2020-04-09 16:09
Thanks for the info. I'll look into the details and keep you posted.

**Comment by rsndates** [comment] 2020-04-09 20:56
Seems there is a zoneset still pending

**Comment by daniel-chung-broadcom** [comment] 2020-04-09 22:55
I am not clear on what are the steps to recreate the problem. Will you be able to share the steps required? Thanks.

**Comment by daniel-chung-broadcom** [comment] 2020-04-27 17:05
after doing some investigation and reading through the thread several times, I think there are two issues being reported here.

1) if cfg is enabled, the effort to delete will fail
2) to_delete_* contains something that has been deleted already, error is returned instead of no change

For #1, I believe it is working as expected. Basically, the underlying FOS Zoning feature does not allow you to delete something that is part of active Cfg. So, if you try to delete a zone that is part of active Cfg, we'll get an error trying to enable the active Cfg after deleting. When we see the error, we abort the transaction and return the error in the playbook.

However, if you delete zone (or alias) that is not part of the active Cfg, that works fine. This is also working as expected.

For #2, I believe that is a bug. I made changes to existing_zone_db branch to see if the zone (alias, or cfg) being delete exists or not and delete only if entries still exist. Otherwise, no change is returned.

Please let me know if these are the issues that are you reporting. Since there has not been as much interactions on this thread, I'll plan to close this issue when the branch is merged to the main. If the issue isn't addressed (or misunderstood), we can open new issues to track those. Thanks

**Comment by daniel-chung-broadcom** [comment] 2020-05-01 16:50
the changes have been merged to main and uplodated to galaxy.ansible.com. Closing the issue as described in the previous post.

**Closed by daniel-chung-broadcom** 2020-05-01 16:50 UTC
