### ISSUE TITLE
Initial setup issue while connecting to switch runnning FOS v8.2.1d

### ISSUE THREAD

**Issue by sri4kanne** [brocade/ansible#22] opened 2020-04-13 18:31 UTC
Hello,
After configuring the initial setup and i am getting below error when trying to run facts task. Not sure if this because of the FOS v8.2.1d that we are trying to connect, can you please take a look and advise?

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: xml.parsers.expat.ExpatError: no element found: line 1, column 0
fatal: [lsfcsw6203]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\", line 56, in login\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 1390, in open_url\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 563, in error\n    result = self._call_chain(*args)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 755, in http_error_302\n    return self.parent.open(new, timeout=req.timeout)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 569, in error\n    return self._call_chain(*args)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 649, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\nurllib.error.HTTPError: HTTP Error 405: Method Not Allowed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/smysoresrinivas/.ansible/tmp/ansible-tmp-1586802389.5118568-93190311158810/AnsiballZ_brocade_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/smysoresrinivas/.ansible/tmp/ansible-tmp-1586802389.5118568-93190311158810/AnsiballZ_brocade_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/smysoresrinivas/.ansible/tmp/ansible-tmp-1586802389.5118568-93190311158810/AnsiballZ_brocade_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\", line 384, in <module>\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\", line 181, in main\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\", line 61, in login\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_ygthf8xl/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_xml.py\", line 44, in bsn_xmltodict\n  File \"/usr/local/lib/python3.7/site-packages/xmltodict.py\", line 327, in parse\n    parser.Parse(xml_input, True)\nxml.parsers.expat.ExpatError: no element found: line 1, column 0\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

ansible 2.9.6
  config file = /Users/smysoresrinivas/Documents/ansible/tasks/ansible.cfg
  configured module search path = ['/Users/smysoresrinivas/Documents/ansible/tasks', '/Users/smysoresrinivas/Documents/ansible/library']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]

Switch config: currently running FOS **v8.2.1d**
mgmtapp --show
REST Interface State: Enabled
REST Session Count: 3
REST Throttling Configurations:
   Sample Requests      : 30
   Sample Time (in sec) : 30
   Idle Time (in sec)   : 3
KeepAlive : Disabled
KeepAliveTimeout : 15sec

**Comment by daniel-chung-broadcom** [comment] 2020-04-14 19:19
Can you please check to see if your security setting is matching between yml file & fos? I noticed something similar when I was doing my own testing recently. 

      https: False

          https: True for HTTPS, self for self-signed HTTPS, or False for HTTP

**Comment by daniel-chung-broadcom** [comment] 2020-04-14 22:36
btw, I believe I have a fix for this if using HTTP when FOS is configured as https true or self. Please let me know if you are seeing the same or different problem.

**Comment by sri4kanne** [comment] 2020-04-15 04:23
Thanks for taking a look @daniel-chung-broadcom.
When I try with “https” it’s failing with below error. I have self signed cert on switch for https which is used to connect to BNA and Expires On: Feb  2 19:00:22 2025 GMT
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
---this seems like a common error with python urllib and tried the fix suggested but with no luck https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

When I’m using “http” seeing below error
fatal: [lsfcsw6203]: FAILED! => {"changed": false, "full_login_Url": "http://10.221.XXX.XX/rest/login", "login_resp_code": 405, "login_resp_data": null, "login_resp_reason": "Method Not Allowed", "lxml_err_msg": "The brocade_xml module requires the xmltodict python library installed on the managed machine", "msg": "failed to login"}

Please let me know if you need any more details that is helpful to narrow down the issue.

PS:I tried "ansible-fos-command" module and that's working fine and able to connect to switch and run commands there.

**Comment by daniel-chung-broadcom** [comment] 2020-04-15 05:19
let's start with the easier one. When you are using http, it looks like you are running into this error "lxml_err_msg": "The brocade_xml module requires the xmltodict python library installed on the managed machine". I typically install xmltodict by using pip command (something like pip install --user xmltodict or python3.5 -m pip install --user xmltodict). xmltodict is a required python library for brocade modules, as well as some other modules by various vendors in ansible distribution. Please install the xmltodict python library for your python env.

As for certficate, you mentioned that you are using self signed on fos? If you are, are you setting https to "self" or "True"? If you are using non-self signed certs, you would want to set the https to True because you want the library to validate the issuer. If fos is self-signed, you want to set https to "self" because you don't want the python library to fail because the cert is self signed.

**Comment by daniel-chung-broadcom** [comment] 2020-04-15 23:54
fyi. I just pushed changes to peer_add_normal_member_only that prevents the crash in case https configurations do not match.

**Comment by sri4kanne** [comment] 2020-04-16 03:44
I did install the module for "http" and got a little further and failed again with below error. 
For "https" when i use "Self" instead of true it's getting a little further but failing with error as for "http" requests.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: xml.parsers.expat.ExpatError: no element found: line 1, column 0
fatal: [lsfcsw6203]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_facts_payload_lbfpwtre/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\", line 56, in login\n  

And i did try the "peer_add_normal_member_only" branch to see if i can get any further with not much luck there too and is failing with below error for both http and https.
fatal: [lsfcsw6203]: FAILED! => {"changed": false, "full_login_Url": "http://10.221.252.26/rest/login", "login_resp_code": 405, "login_resp_data": "", "login_resp_reason": "Method Not Allowed", "msg": "failed to login"}

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 04:09
it says "failed to login", and "Method Not Allowed".

I am wondering if you have rest disabled. What do you see if you do mgmtapp --show. Does it show that rest is enabled? I tried disabling rest on my switch but I am getting "forbidden" error instead. But just wanted to confirm in case err message has changed.

**Comment by sri4kanne** [comment] 2020-04-16 04:59
I had posted this before too just want to point out the we just upgraded and in the process of upgrading brocades to FOS v8.2.1d and same version is running on the switch i'm trying to connect.
lsfcsw6203:admin> mgmtapp --show
REST Interface State: Enabled
REST Session Count: 3
REST Throttling Configurations:
   Sample Requests      : 30
   Sample Time (in sec) : 30
   Idle Time (in sec)   : 3
KeepAlive : Disabled
KeepAliveTimeout : 15sec

Also when i run module in verbose mode seeing "urllib.error.HTTPError: HTTP Error 405: Method Not Allowed" along with "xml.parsers.expat.ExpatError: no element found:" for the master branch too.

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 14:40
can you please double confirm (I think you said it in the original comment) that you are running 8.2.1d on the switch in question? I am trying to research under which circumstance REST API will return "method no allowed" for login URL. I'll keep you posted.

I have a fix for "no element found" in the side branch I mentioned in the thread. It should now return an error structure upon login failure.

**Comment by sri4kanne** [comment] 2020-04-16 15:59
Yes it is and it's a G630 switch.
admin> firmwareshow
Appl     Primary/Secondary Versions
------------------------------------------
FOS      v8.2.1d
         v8.2.1d

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 16:03
Thanks. I'll keep you posted on my research.

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 17:26
We are still investigating. What I am told at the moment is that the error indicates that we are doing operations that "rest/login" URL doesn't support. For example, I believe "rest/login" supports POST. So, I can create the same error by changing "POST" operation to "PATCH".

Can you please check to see if line #56 in brocade_connection.py still shows "POST"? I cannot imagine why this would have been changed to something else but just leaving no stone unturned.
 
Here is what I see in my output if I change the login operation from POST to PATCH.

fatal: [san_eng_zone_seed_san_a]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "full_login_Url": "http://10.155.107.74/rest/login", "login_resp_code": 405, "login_resp_data": "", "login_resp_reason": "Method Not Allowed", "msg": "failed to login"}

**Comment by sri4kanne** [comment] 2020-04-16 18:30
Thanks for looking into this.  Yes in line 56 i see a "POST" call being made in both master and other branch you have posted earlier.

Below is the error snippet that i'm getting.
fatal: [lsfcsw6203]: FAILED! => {"changed": false, "full_login_Url": "http://XX.XX.XXX.XXX/rest/login", "login_resp_code": 405, "login_resp_data": "", "login_resp_reason": "Method Not Allowed", "msg": "failed to login"}

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 18:33
Ok. I think we have a theory. Since we really cannot think of any reason why the code would be changed, one scenario that we are able to reproduce the same output is

1) set the switch in self-signed https
2) using https False in the playbook.

Can you please check the output of

seccertmgmt show -cert https

to see if the switch in question has self-signed cert installed or not? If so, can you please remove the cert & try the playbook with https set to False?

Thanks.

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 18:38
Also, I think you said that "Self" was used. It should actually be "self". Another way to repro the problem was for me to

1) set the switch in self-signed mode
2) use "Self" instead of "self" for https in the playbook.

here is the output when I used "Self".

fatal: [san_eng_zone_seed_san_a]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "full_login_Url": "http://10.155.107.74/rest/login", "login_resp_code": 405, "login_resp_data": "", "login_resp_reason": "Method Not Allowed", "msg": "failed to login"}

Here is the output of the same playbook when using "self"

dc400196@iaas-l-2206-611:~/ansible/tasks$ ansible-playbook -i ../san-inventory test.yml

PLAY [san_eng_zone_seed_san_a] *************************************************

TASK [enable root & user] ******************************************************
ok: [san_eng_zone_seed_san_a]

PLAY RECAP *********************************************************************
san_eng_zone_seed_san_a    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 18:45
Looking at the code, I check to see if https is boolean (true or false) or match to "self". Otherwise, I default to https False. Which means that if you used "Self", its behavior would have been the same as "https False" and would match my earlier theory that the switch is self-signed & https is set to False. 

I'll plan to change the code to handle the comparison to self as case insensitive regardless of your experiment since I could see how that could be confusing between "True/False/self" instead of "True/False/Self".

**Comment by sri4kanne** [comment] 2020-04-16 18:49
Using "self" seems to have fixed it all. Thank you for your help looking into this.

**Comment by daniel-chung-broadcom** [comment] 2020-04-16 19:16
Great. :-)

**Comment by daniel-chung-broadcom** [comment] 2020-04-20 15:57
merged to main support for case insensitive parsing of "self" and proper parsing of error during login if https/http mode does not match between playbook and fos. published collection to galaxy.ansible.com as well. closing the issue.

**Closed by daniel-chung-broadcom** 2020-04-20 15:57 UTC
