### ISSUE TITLE
Task skipping in find_ns_by_pwwn.yml

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#49] opened 2020-07-08 20:55 UTC
After cloning the current repo few mins back and when I tried to run the find_ns_by_pwwn.yml playbook I see one of the task   "print device information matching port_name" is skipping even though the WWN I mentioned is logged into switch port.

PLAY [all] **********************************************************************************************************************************************************************************

TASK [gather device info] *******************************************************************************************************************************************************************
ok: [test_switch]

**TASK [print device information matching port_name] ******************************************************************************************************************************************
skipping: [test_switch]**

TASK [gather device alias info] *************************************************************************************************************************************************************
ok: [test_switch]

TASK [print device alias information matching port_name] ************************************************************************************************************************************
ok: [test_switch] => {
    "ansible_facts['alias']": [
        {
            "alias-name": "target_4", 
            "member-entry": {
                "alias-entry-name": "50:xx:xx:xx:xx:xx:xx:xx"
            }
        }
    ]
}

PLAY RECAP **********************************************************************************************************************************************************************************
test_switch                   : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment] 2020-07-08 23:45
Let me give it a try and see if anything changed since. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment] 2020-07-09 00:04
found the problem. I updated the facts code to return the content that matches the playbook variable definitions (fibrechannel_name_server instead of fibrechannel-name-server) for consistent display but didn't realize that the string was being used as index here. Can you please try find_pwwn_fix branch?

**Comment by daniel-chung-broadcom** [comment] 2020-07-09 04:32
changes were pretty isolated. So, I went ahead and merge to the master. Please check it out and let me know if the changes are good. Thanks.

**Comment by autocoder10** [comment] 2020-07-09 16:51
Looks good now. Thanks.

**Comment by daniel-chung-broadcom** [comment] 2020-07-09 17:02
sorry for the regression. I'll close the issue since already merged to master.

**Closed by daniel-chung-broadcom** 2020-07-09 17:02 UTC
