### ISSUE TITLE
brocade_lst_obj doesn't add all MAPS-rules to a policy

### ISSUE THREAD

**Issue by amoklilli** [brocade/ansible#79] opened 2021-02-18 06:38 UTC
Using the generic brocade_lst_obj I'm adding default-rules to a new or existing MAPS-policy.
But only half the rules is added to the policy, ansible reports success.

Example of Rules to add:
        - defNON_E_F_PORTSPE_2
        - defALL_HOST_PORTSITW_15
        - defALL_OTHER_SFPCURRENT_50
        - defALL_E_PORTSITW_15

Only the first and third rule is added to the policy. In a second run of ansible, the result is the same (only first and third). If I change the order of the rules to import, the result is still the same(only first and third).

Importing the rules using a python-script POSTing to the REST-API directly, all rules a added to the policy. Brocade-Support confirmed that the switch is working correctly. Result is the same in FOS v8.2.2b and v9.0.0b.

Any idea?
[maps-policy-playbook.zip](https://github.com/brocade/ansible/files/6000706/maps-policy-playbook.zip)

**Comment by daniel-chung-broadcom** [comment] 2021-02-18 16:56
Thanks for providing the get and set playbook examples. Let me see if I could repro the issue and do some investigation and get back to you. BTW, are you using galaxy download or clone from githib.com/brocade/ansible? Thanks.

**Comment by amoklilli** [comment] 2021-02-18 18:26
We are using the clone from github.com/brocade/ansible. But since our systems are somewhat airgapped we downloaded the master.zip via the Webgui. Will download again tomorrow and check if there are any differences in the code. Will try again with the latest version. Thanks.

**Comment by daniel-chung-broadcom** [comment] 2021-02-18 18:32
I have repro'ed the problem but we are still investigating the root cause of the issue. I am using the latest version. So, I wouldn't think that upgrading on your side will make any difference. I'll keep you posted on the progress of the investigation.

**Comment by daniel-chung-broadcom** [comment] 2021-02-20 01:18
I have the changes that I believe should address your issue on documentation_attribute_content_change. When you get a chance, can you please try out the branch and let me know if you still see the issue? Thanks.

**Comment by amoklilli** [comment] 2021-02-20 09:19
Thanks for the reply. Will try it on monday. Have a nice weekend!

**Comment by amoklilli** [comment] 2021-02-22 10:59
Hi,

tested and working as expected now.

Thank you!

**Comment by daniel-chung-broadcom** [comment] 2021-02-22 16:59
Thanks for the update. I typically leave the issue opened until we have a chance to merge the changes into master and also update the ansible collection. I also typically wait until few of these issues were collected instead of updating the collection each time. Let me know if any issues with the process and leaving the issue opened. Thanks.

**Comment by amoklilli** [comment] 2021-02-22 18:10
No, that's fine with me. Sorry for the inconvenience.
Thanks again for the help.

**Comment by munokar** [comment] 2022-05-17 15:50
Hi,
are you planing any new release to ansible galaxy within the next time.
Has been some time since your last release.
I triggered the same issue described above and would love to see that fixed in the modules provided through ansible galaxy.
Thanks and kind regards

**Comment by prasad-valmeti-broadcom** [comment] 2022-12-11 05:34
This is just to give an update. Plan is in progress to merge documentation branch changes into main/galaxy. Will update once the plan is finalized.

**Comment by prasad-valmeti-broadcom** [comment] 2023-09-08 23:04
The issue is already addressed in Ansible FOS 1.3.3. If there are no further issues, please suggest if we can close the issue.

**Comment by amoklilli** [comment] 2023-09-09 10:18
Yes you may close this issue.
Thank you!

**Closed** 2023-09-11 17:46 UTC
